"""add content_ko and source_type to interpretation_chunks

Revision ID: 6e421e60c756
Revises: 3642be719bfd
Create Date: 2026-08-14 19:00:51.534793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e421e60c756'
down_revision: Union[str, Sequence[str], None] = '3642be719bfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interpretation_chunks', sa.Column('source_type', sa.String(length=30), nullable=True))
    op.add_column('interpretation_chunks', sa.Column('content_ko', sa.Text(), nullable=True))
    op.create_index(op.f('ix_interpretation_chunks_source_type'), 'interpretation_chunks', ['source_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interpretation_chunks_source_type'), table_name='interpretation_chunks')
    op.drop_column('interpretation_chunks', 'content_ko')
    op.drop_column('interpretation_chunks', 'source_type')
    # ### end Alembic commands ###
